version: '3.9'

services:

  mysql:
      image: mariadb:10.6.4-focal
      restart: always
      container_name: mysql
      hostname: mysql
      command: '--default-authentication-plugin=mysql_native_password'
      environment:
        MYSQL_USER: 'root'
        MYSQL_PASSWORD: '123'
        MYSQL_ROOT_PASSWORD: '123'
        MYSQL_DATABASE: 'Ridely'
      expose:
        - 3306
      volumes:
        - ./sql/:/app
      networks: 
        - ridely

  ridely-passenger:
    depends_on:
      - mysql
    build: 
      context: ./Passenger
      dockerfile: Dockerfile.passenger
    ports:
      - 5000:5000
    restart: always
    volumes:
      - ./Passenger/:/app
    networks:
      - ridely
    
  ridely-driver:
    depends_on:
      - mysql
    build: 
      context: ./Driver
      dockerfile: Dockerfile.driver
    ports:
      - 5001:5001
    restart: always
    volumes:
      - ./Driver/:/app
    networks:
      - ridely

  ridely-trips:
    depends_on:
      - mysql
    build: 
      context: ./Trips
      dockerfile: Dockerfile.trip
    ports:
      - 5002:5002
    restart: always
    volumes:
      - ./Trips/:/app
    networks:
      - ridely

  ridely-frontend:
    depends_on:
      - ridely-passenger
      - ridely-driver
      - ridely-trips
    build: 
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/app
    command: npm run dev
    networks:
      - ridely

volumes:
  node_modules:

networks:
  ridely:
    driver: bridge
  
