version: '3.8'

services:
  ridely-frontend:
    depends_on:
      - ridely-passenger
      - ridely-driver
      - ridely-trips
    build: 
      context: ./frontend
    image: ubotter/ridely-frontend:latest
    container_name: nextjs-frontend
    hostname: nextjs-frontend
    ports:
      - 3000:3000

  ridely-passenger:
    depends_on:
      - mysql
    build: 
      context: ./Passenger
    image: ubotter/ridely-passenger:latest
    container_name: ridely-passenger
    hostname: ridely-passenger
    ports:
      - 5000:5000
    environment:
      - 'DB_PORT=6033'
      - 'DB_HOST=ridely-mysql'
    deploy:
      restart_policy:
        condition: on-failure
  ridely-driver:
    depends_on:
      - mysql
    build: 
      context: ./Driver
    image: ubotter/ridely-driver:latest
    container_name: ridely-driver
    hostname: ridely-driver
    ports:
      - 5001:5001
    environment:
      - 'DB_PORT=6033'
    deploy:
      restart_policy:
        condition: on-failure

  ridely-trips:
    depends_on:
      - ridely-passenger
      - ridely-driver
    build: 
      context: ./Trips
    image: ubotter/ridely-trip:latest
    container_name: ridely-trip
    hostname: ridely-trip
    ports:
      - 5002:5002
    environment:
      - 'DB_PORT=6033'
    deploy:
      restart_policy:
        condition: on-failure

  mysql:
    image: mysql/mysql-server:latest
    restart: unless-stopped
    container_name: mysql
    environment:
      - 'MYSQL_USER=root'
      - 'MYSQL_PASSWORD=123'
      - 'MYSQL_ROOT_PASSWORD:123'
      - 'MYSQL_DATABASE:Ridely'
    ports: 
      - 3306:3306

volumes:
  mysql: 
